#version: "3"
#services:
#    app:
#        build:
#           context: .
#            dockerfile: ./Dockerfile
#        image: image-platform
#        p3rts:
#            - 81:80
#        env_file: .env
#        volumes:
#            - .:/var/www/app
#        working_dir: /var/www/app
version: '3'
services:
    php:
        image: image-platform
        build: ./php-fpm
        volumes:
            - ./trb-platform:/var/www/trb-platform
            - ./php-fpm/php.ini:/usr/local/etc/php/php.ini

    web:
        image: nginx:latest
        ports:
            - "8888:80"
        volumes:
            - ./trb-platform:/var/www/trb-platform
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
