version: '3'
services:
    php:
        image: image-platform
        build: ./Dockerfile
        volumes:
            - ./trb-platform:/var/www/trb-platform
            #- ./php-fpm/php.ini:/usr/local/etc/php/php.ini
    web:
        image: nginx:latest
        ports:
            - "8888:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./trb-platform:/var/www/trb-platform
        depends_on:
            - php
