<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.MnNiUch' shared service.

return $this->privates['.service_locator.MnNiUch'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'projectsRepository' => ['privates', 'App\\Repository\\ProjectsRepository', 'getProjectsRepositoryService.php', true],
]);
