<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.no19fnv' shared service.

return $this->privates['.service_locator.no19fnv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'clientRegistry' => ['services', 'knpu.oauth2.registry', 'getKnpu_Oauth2_RegistryService.php', true],
]);
