<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.MWuXu_8' shared service.

return $this->privates['.service_locator.MWuXu_8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'engineersRepository' => ['privates', 'App\\Repository\\EngineersRepository', 'getEngineersRepositoryService.php', true],
]);
