<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'knpu.oauth2.client.keycloak' shared service.

include_once $this->targetDirs[3].'\\vendor\\knpuniversity\\oauth2-client-bundle\\src\\Client\\OAuth2ClientInterface.php';
include_once $this->targetDirs[3].'\\vendor\\knpuniversity\\oauth2-client-bundle\\src\\Client\\OAuth2Client.php';
include_once $this->targetDirs[3].'\\vendor\\knpuniversity\\oauth2-client-bundle\\src\\Client\\Provider\\KeycloakClient.php';
include_once $this->targetDirs[3].'\\vendor\\league\\oauth2-client\\src\\Tool\\ArrayAccessorTrait.php';
include_once $this->targetDirs[3].'\\vendor\\league\\oauth2-client\\src\\Tool\\QueryBuilderTrait.php';
include_once $this->targetDirs[3].'\\vendor\\league\\oauth2-client\\src\\Provider\\AbstractProvider.php';
include_once $this->targetDirs[3].'\\vendor\\league\\oauth2-client\\src\\Tool\\BearerAuthorizationTrait.php';
include_once $this->targetDirs[3].'\\vendor\\stevenmaguire\\oauth2-keycloak\\src\\Provider\\Keycloak.php';
include_once $this->targetDirs[3].'\\vendor\\knpuniversity\\oauth2-client-bundle\\src\\DependencyInjection\\ProviderFactory.php';

return $this->services['knpu.oauth2.client.keycloak'] = new \KnpU\OAuth2ClientBundle\Client\Provider\KeycloakClient((new \KnpU\OAuth2ClientBundle\DependencyInjection\ProviderFactory(($this->services['router'] ?? $this->getRouterService())))->createProvider('Stevenmaguire\\OAuth2\\Client\\Provider\\Keycloak', ['clientId' => $this->getEnv('OAUTH_KEYCLOAK_CLIENT_ID'), 'clientSecret' => $this->getEnv('OAUTH_KEYCLOAK_CLIENT_SECRET'), 'authServerUrl' => $this->getEnv('OAUTH_KEYCLOAK_AUTH_URL'), 'realm' => $this->getEnv('OAUTH_KEYCLOAK_REALM'), 'encryptionAlgorithm' => NULL, 'encryptionKeyPath' => NULL, 'encryptionKey' => NULL], 'connect_keycloak_check', [], []), ($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
