<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Security\KeycloakAuthenticator' shared autowired service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\security-http\\EntryPoint\\AuthenticationEntryPointInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\security-guard\\AuthenticatorInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\security-guard\\AbstractGuardAuthenticator.php';
include_once $this->targetDirs[3].'\\vendor\\knpuniversity\\oauth2-client-bundle\\src\\Security\\Helper\\FinishRegistrationBehavior.php';
include_once $this->targetDirs[3].'\\vendor\\knpuniversity\\oauth2-client-bundle\\src\\Security\\Helper\\PreviousUrlHelper.php';
include_once $this->targetDirs[3].'\\vendor\\knpuniversity\\oauth2-client-bundle\\src\\Security\\Helper\\SaveAuthFailureMessage.php';
include_once $this->targetDirs[3].'\\vendor\\knpuniversity\\oauth2-client-bundle\\src\\Security\\Authenticator\\SocialAuthenticator.php';
include_once $this->targetDirs[3].'\\src\\Security\\KeycloakAuthenticator.php';
include_once $this->targetDirs[3].'\\src\\Services\\HttpClientKeycloakInterface.php';
include_once $this->targetDirs[3].'\\src\\Factory\\ManagerFactory.php';
include_once $this->targetDirs[3].'\\src\\Services\\RancherClientInterface.php';
include_once $this->targetDirs[3].'\\src\\Services\\RancherClient.php';
include_once $this->targetDirs[3].'\\src\\Helper\\Utility.php';
include_once $this->targetDirs[3].'\\vendor\\knpuniversity\\oauth2-client-bundle\\src\\Client\\ClientRegistry.php';

$a = ($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService());

return $this->privates['App\\Security\\KeycloakAuthenticator'] = new \App\Security\KeycloakAuthenticator(($this->services['knpu.oauth2.registry'] ?? ($this->services['knpu.oauth2.registry'] = new \KnpU\OAuth2ClientBundle\Client\ClientRegistry($this, ['keycloak' => 'knpu.oauth2.client.keycloak']))), (new \App\Factory\ManagerFactory())->switchService($this, $a), new \App\Services\RancherClient($a, new \App\Helper\Utility()), $this);
