<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.access_map' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\security-http\\AccessMapInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\security-http\\AccessMap.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-foundation\\RequestMatcherInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-foundation\\RequestMatcher.php';

$this->privates['security.access_map'] = $instance = new \Symfony\Component\Security\Http\AccessMap();

$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/alstom'), [0 => 'ROLE_ALSTOM_ADMIN', 1 => 'ROLE_ALSTOM_DESIGN', 2 => 'ROLE_ALSTOM_COMMISSIONER', 3 => 'ROLE_ALSTOM_MAINTENER', 4 => 'ROLE_ALSTOM_SERVICE'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/alstom/maintener/association'), [0 => 'ROLE_ALSTOM_MAINTENER'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/client'), [0 => 'ROLE_CLIENT_USER', 1 => 'ROLE_CLIENT_ADMIN'], NULL);

return $instance;
