knpu_oauth2_client:
  clients:
    keycloak:
      # must be "keycloak" - it activates that type!
      type: keycloak
      # add and configure client_id and client_secret in parameters.yml
      client_id: '%env(OAUTH_KEYCLOAK_CLIENT_ID)%'
      client_secret: '%env(OAUTH_KEYCLOAK_CLIENT_SECRET)%'
      # a route name you'll create
      redirect_route: connect_keycloak_check
      redirect_params: {}
      # Keycloak server URL
      auth_server_url: '%env(OAUTH_KEYCLOAK_AUTH_URL)%'
      # Keycloak realm
      realm: '%env(OAUTH_KEYCLOAK_REALM)%'
      # Optional: Encryption algorith, i.e. RS256
      # encryption_algorithm: ''
      # Optional: Encryption key path, i.e. ../key.pem
      # encryption_key_path: ''
      # Optional: Encryption key, i.e. contents of key or certificate
      # encryption_key: ''
      # whether to check OAuth2 "state": defaults to true
      # use_state: true

    # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
