<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Engineers extends \App\Entity\Engineers implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Engineers' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Engineers' . "\0" . 'profile_picture', '' . "\0" . 'App\\Entity\\Engineers' . "\0" . 'filename', '' . "\0" . 'App\\Entity\\Engineers' . "\0" . 'Name', '' . "\0" . 'App\\Entity\\Engineers' . "\0" . 'Surname', '' . "\0" . 'App\\Entity\\Engineers' . "\0" . 'Num_Badge', '' . "\0" . 'App\\Entity\\Engineers' . "\0" . 'Projects', '' . "\0" . 'App\\Entity\\Engineers' . "\0" . 'updated_at'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Engineers' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Engineers' . "\0" . 'profile_picture', '' . "\0" . 'App\\Entity\\Engineers' . "\0" . 'filename', '' . "\0" . 'App\\Entity\\Engineers' . "\0" . 'Name', '' . "\0" . 'App\\Entity\\Engineers' . "\0" . 'Surname', '' . "\0" . 'App\\Entity\\Engineers' . "\0" . 'Num_Badge', '' . "\0" . 'App\\Entity\\Engineers' . "\0" . 'Projects', '' . "\0" . 'App\\Entity\\Engineers' . "\0" . 'updated_at'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Engineers $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $Name): \App\Entity\Engineers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$Name]);

        return parent::setName($Name);
    }

    /**
     * {@inheritDoc}
     */
    public function getSurname(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSurname', []);

        return parent::getSurname();
    }

    /**
     * {@inheritDoc}
     */
    public function setSurname(string $Surname): \App\Entity\Engineers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSurname', [$Surname]);

        return parent::setSurname($Surname);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumBadge(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumBadge', []);

        return parent::getNumBadge();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumBadge(int $Num_Badge): \App\Entity\Engineers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumBadge', [$Num_Badge]);

        return parent::setNumBadge($Num_Badge);
    }

    /**
     * {@inheritDoc}
     */
    public function getProjects(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProjects', []);

        return parent::getProjects();
    }

    /**
     * {@inheritDoc}
     */
    public function addProject(\App\Entity\Projects $project): \App\Entity\Engineers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProject', [$project]);

        return parent::addProject($project);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProject(\App\Entity\Projects $project): \App\Entity\Engineers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProject', [$project]);

        return parent::removeProject($project);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfilePicture(): ?\Symfony\Component\HttpFoundation\File\File
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfilePicture', []);

        return parent::getProfilePicture();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfilePicture(?\Symfony\Component\HttpFoundation\File\File $profile_picture): \App\Entity\Engineers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfilePicture', [$profile_picture]);

        return parent::setProfilePicture($profile_picture);
    }

    /**
     * {@inheritDoc}
     */
    public function getFilename(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFilename', []);

        return parent::getFilename();
    }

    /**
     * {@inheritDoc}
     */
    public function setFilename(?string $filename): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFilename', [$filename]);

        parent::setFilename($filename);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTimeInterface $updated_at): \App\Entity\Engineers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updated_at]);

        return parent::setUpdatedAt($updated_at);
    }

}
