<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Equipement extends \App\Entity\Equipement implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Equipement' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Equipement' . "\0" . 'AssociationEquiptERTMS', '' . "\0" . 'App\\Entity\\Equipement' . "\0" . 'DTR_board', '' . "\0" . 'App\\Entity\\Equipement' . "\0" . 'Indice_DTR', '' . "\0" . 'App\\Entity\\Equipement' . "\0" . 'Num_serie', '' . "\0" . 'App\\Entity\\Equipement' . "\0" . 'type', '' . "\0" . 'App\\Entity\\Equipement' . "\0" . 'SousType', '' . "\0" . 'App\\Entity\\Equipement' . "\0" . 'assocEvcCarte', '' . "\0" . 'App\\Entity\\Equipement' . "\0" . 'Status'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Equipement' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Equipement' . "\0" . 'AssociationEquiptERTMS', '' . "\0" . 'App\\Entity\\Equipement' . "\0" . 'DTR_board', '' . "\0" . 'App\\Entity\\Equipement' . "\0" . 'Indice_DTR', '' . "\0" . 'App\\Entity\\Equipement' . "\0" . 'Num_serie', '' . "\0" . 'App\\Entity\\Equipement' . "\0" . 'type', '' . "\0" . 'App\\Entity\\Equipement' . "\0" . 'SousType', '' . "\0" . 'App\\Entity\\Equipement' . "\0" . 'assocEvcCarte', '' . "\0" . 'App\\Entity\\Equipement' . "\0" . 'Status'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Equipement $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getAssociationEquiptERTMS()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAssociationEquiptERTMS', []);

        return parent::getAssociationEquiptERTMS();
    }

    /**
     * {@inheritDoc}
     */
    public function setAssociationEquiptERTMS($AssociationEquiptERTMS): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAssociationEquiptERTMS', [$AssociationEquiptERTMS]);

        parent::setAssociationEquiptERTMS($AssociationEquiptERTMS);
    }

    /**
     * {@inheritDoc}
     */
    public function getDTRBoard(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDTRBoard', []);

        return parent::getDTRBoard();
    }

    /**
     * {@inheritDoc}
     */
    public function setDTRBoard(string $DTR_board): \App\Entity\Equipement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDTRBoard', [$DTR_board]);

        return parent::setDTRBoard($DTR_board);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndiceDTR(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndiceDTR', []);

        return parent::getIndiceDTR();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndiceDTR(string $Indice_DTR): \App\Entity\Equipement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndiceDTR', [$Indice_DTR]);

        return parent::setIndiceDTR($Indice_DTR);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumSerie(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumSerie', []);

        return parent::getNumSerie();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumSerie(string $Num_serie): ?\App\Entity\Equipement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumSerie', [$Num_serie]);

        return parent::setNumSerie($Num_serie);
    }

    /**
     * {@inheritDoc}
     */
    public function getType(): ?\App\Entity\TypeEquipement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setType(?\App\Entity\TypeEquipement $type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getSousType(): ?\App\Entity\SoustypeEquipement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSousType', []);

        return parent::getSousType();
    }

    /**
     * {@inheritDoc}
     */
    public function setSousType(?\App\Entity\SoustypeEquipement $SousType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSousType', [$SousType]);

        return parent::setSousType($SousType);
    }

    /**
     * {@inheritDoc}
     */
    public function getAssocEvcCarte(): ?\App\Entity\AssocEvcCarte
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAssocEvcCarte', []);

        return parent::getAssocEvcCarte();
    }

    /**
     * {@inheritDoc}
     */
    public function setAssocEvcCarte(?\App\Entity\AssocEvcCarte $assocEvcCarte): \App\Entity\Equipement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAssocEvcCarte', [$assocEvcCarte]);

        return parent::setAssocEvcCarte($assocEvcCarte);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(?bool $Status): \App\Entity\Equipement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$Status]);

        return parent::setStatus($Status);
    }

}
