<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1V8xTuc\srcApp_KernelProdDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1V8xTuc/srcApp_KernelProdDebugContainer.php') {
    touch(__DIR__.'/Container1V8xTuc.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdDebugContainer::class, false)) {
    \class_alias(\Container1V8xTuc\srcApp_KernelProdDebugContainer::class, srcApp_KernelProdDebugContainer::class, false);
}

return new \Container1V8xTuc\srcApp_KernelProdDebugContainer([
    'container.build_hash' => '1V8xTuc',
    'container.build_id' => 'baca5d61',
    'container.build_time' => 1562245238,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1V8xTuc');
