<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerABozU4x\srcApp_KernelProdDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerABozU4x/srcApp_KernelProdDebugContainer.php') {
    touch(__DIR__.'/ContainerABozU4x.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdDebugContainer::class, false)) {
    \class_alias(\ContainerABozU4x\srcApp_KernelProdDebugContainer::class, srcApp_KernelProdDebugContainer::class, false);
}

return new \ContainerABozU4x\srcApp_KernelProdDebugContainer([
    'container.build_hash' => 'ABozU4x',
    'container.build_id' => 'b2abe5c0',
    'container.build_time' => 1564389706,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerABozU4x');
