<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGdQDovz\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGdQDovz/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerGdQDovz.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerGdQDovz\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerGdQDovz\srcApp_KernelProdContainer([
    'container.build_hash' => 'GdQDovz',
    'container.build_id' => '46cfc664',
    'container.build_time' => 1564413051,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGdQDovz');
