<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container79afyjB\srcApp_KernelProdDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container79afyjB/srcApp_KernelProdDebugContainer.php') {
    touch(__DIR__.'/Container79afyjB.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdDebugContainer::class, false)) {
    \class_alias(\Container79afyjB\srcApp_KernelProdDebugContainer::class, srcApp_KernelProdDebugContainer::class, false);
}

return new \Container79afyjB\srcApp_KernelProdDebugContainer([
    'container.build_hash' => '79afyjB',
    'container.build_id' => '3c549d11',
    'container.build_time' => 1561108245,
], __DIR__.\DIRECTORY_SEPARATOR.'Container79afyjB');
