<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBmywgYD\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBmywgYD/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBmywgYD.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBmywgYD\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerBmywgYD\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'BmywgYD',
    'container.build_id' => 'aaa7caac',
    'container.build_time' => 1569394658,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBmywgYD');
