<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAubxSs2\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAubxSs2/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAubxSs2.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAubxSs2\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerAubxSs2\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'AubxSs2',
    'container.build_id' => '356acac2',
    'container.build_time' => 1565807163,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAubxSs2');
