<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEBrDQDm\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEBrDQDm/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEBrDQDm.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEBrDQDm\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerEBrDQDm\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'EBrDQDm',
    'container.build_id' => '5b1b96fe',
    'container.build_time' => 1566375206,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEBrDQDm');
