#index:
#    path: /
#    controller: App\Controller\DefaultController::index

alstom.home:
  path: /alstom
  controller: App\Controller\alstomController:index
alstom.client:
  path: /alstom/clients
  controller: App\Controller\alstomController:clients


client.home:
  path: /client
  controller: App\Controller\clientController:index