#Routes à définir pour le login

login:
  path: /login
  defaults:
    _controller: TestBundle:Security:login
login_check:
  path: /login_check
logout:
  path: /logout




#Partie de toutes les vue d'alstom
#Homepage Alstom
alstom.home:
  path: /alstom
  controller: App\Controller\alstomController:index
#  Vue se rapportant à l'onglet client
alstom.client:
  path: /alstom/clients
  controller: App\Controller\alstomController:clients
alstom.client-show:
  path: /alstom/clients/{id}
  controller: App\Controller\alstomController:show_clients
alstom.create-client:
  path: /alstom/create-clients
  controller: App\Controller\alstomController:create_clients
alstom.edit-client:
  path: /alstom/edit-client/{id}
  controller: App\Controller\alstomController:edit_client
  methods: GET|POST
alstom.delete-client:
  path: /alstom/client/{id}
  controller: App\Controller\alstomController:delete_client
  methods: DELETE

#  Vue se rapportant à l'onglet engineers
alstom.engineers:
  path: /alstom/engineers
  controller: App\Controller\alstomController:engineers
alstom.engineer-show:
    path: /alstom/engineer/{id}
    controller: App\Controller\alstomController:show_engineer
alstom.create-engineer:
    path: /alstom/create-engineer
    controller: App\Controller\alstomController:create_engineer
alstom.edit-engineer:
    path: /alstom/edit-engineer/{id}
    controller: App\Controller\alstomController:edit_engineer
    methods: GET|POST
alstom.delete-engineer:
  path: /alstom/engineer/{id}/delete
  controller: App\Controller\alstomController:delete_engineer
  methods: DELETE

# Vue se rapportant à l'onglet projects
alstom.projects:
  path: /alstom/projects
  controller: App\Controller\alstomController:projects
alstom.project-show:
    path: /alstom/project/{id}
    controller: App\Controller\alstomController:show_project
alstom.create-project:
  path: /alstom/create-project
  controller: App\Controller\alstomController:create_project
alstom.edit-project:
  path: /alstom/edit-project/{id}
  controller: App\Controller\alstomController:edit_project
  methods: GET|POST
alstom.delete-project:
  path: /alstom/project/{id}/delete
  controller: App\Controller\alstomController:delete_project
  methods: DELETE

# Vue se rapportant à l'onglet trains
alstom.trains:
  path: /alstom/trains
  controller: App\Controller\alstomController:trains
alstom.show-train:
  path: /alstom/trains/{id}
  controller: App\Controller\alstomController:show_train



#Vue du client
client.home:
  path: /client
  controller: App\Controller\clientController:index
#Projects
client.projects:
  path: /client/projects
  controller: App\Controller\clientController:projects
client.project-show:
  path: /client/project/{id}
  controller: App\Controller\clientController:show_project
#Trains
client.trains:
  path: /client/trains
  controller: App\Controller\clientController:trains
client.create-train:
  path: /client/create-train
  controller: App\Controller\clientController:create_train
client.show-train:
  path: /client/trains/{id}
  controller: App\Controller\clientController:show_train
client.edit-train:
  path: /client/edit-train/{id}
  controller: App\Controller\clientController:edit_train
client.delete-train:
  path: /client/train/{id}
  controller: App\Controller\clientController:delete_train
  methods: DELETE