#Partie de toutes les vue d'alstom
#Homepage
alstom.home:
  path: /alstom
  controller: App\Controller\alstomController:index
#  Vue ce rapportant à l'onglet client
alstom.client:
  path: /alstom/clients
  controller: App\Controller\alstomController:clients
alstom.create-client:
  path: /alstom/create-clients
  controller: App\Controller\alstomController:create_clients
alstom.edit-client:
  path: /alstom/client/{id}
  controller: App\Controller\alstomController:edit_client
  methods: GET|POST
alstom.delete-client:
  path: /alstom/client/{id}
  controller: App\Controller\alstomController:delete_client
  methods: DELETE
#  Vue ce rapportant à l'onglet engineers
alstom.engineers:
  path: /alstom/engineers
  controller: App\Controller\alstomController:engineers
alstom.create-engineer:
    path: /alstom/create-engineer
    controller: App\Controller\alstomController:create_engineer
alstom.edit-engineer:
    path: /alstom/engineer/{id}
    controller: App\Controller\alstomController:edit_engineer
    methods: GET|POST
alstom.delete-engineer:
  path: /alstom/engineer/{id}
  controller: App\Controller\alstomController:delete_engineer
  methods: DELETE





client.home:
  path: /client/{id}
  controller: App\Controller\clientController:index