<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.2hlHMKT' shared service.

return $this->privates['.service_locator.2hlHMKT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'baseline' => ['privates', '.errored..service_locator.2hlHMKT.App\\Entity\\Baseline', NULL, 'Cannot autowire service ".service_locator.2hlHMKT": it references class "App\\Entity\\Baseline" but no such service exists.'],
]);
