<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.3t_vtDk' shared service.

return $this->privates['.service_locator.3t_vtDk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'EVC' => ['privates', '.errored..service_locator.3t_vtDk.App\\Entity\\EVC', NULL, 'Cannot autowire service ".service_locator.3t_vtDk": it references class "App\\Entity\\EVC" but no such service exists.'],
]);
