<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.kRdOC71' shared service.

return $this->privates['.service_locator.kRdOC71'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'EVCRepository' => ['privates', 'App\\Repository\\EVCRepository', 'getEVCRepositoryService.php', true],
]);
