<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\TraceableValueResolver.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\KeyCloakAuthController::connectAction' => ['privates', '.service_locator.no19fnv', 'get_ServiceLocator_No19fnvService.php', true],
    'App\\Controller\\alstomController::baseline' => ['privates', '.service_locator.hzCL1kd', 'get_ServiceLocator_HzCL1kdService.php', true],
    'App\\Controller\\alstomController::clients' => ['privates', '.service_locator.jNTV7Lm', 'get_ServiceLocator_JNTV7LmService.php', true],
    'App\\Controller\\alstomController::delete_baseline' => ['privates', '.service_locator.2hlHMKT', 'get_ServiceLocator_2hlHMKTService.php', true],
    'App\\Controller\\alstomController::delete_client' => ['privates', '.service_locator._IXm1YU', 'get_ServiceLocator_IXm1YUService.php', true],
    'App\\Controller\\alstomController::delete_engineer' => ['privates', '.service_locator.tx3hRNe', 'get_ServiceLocator_Tx3hRNeService.php', true],
    'App\\Controller\\alstomController::delete_evc' => ['privates', '.service_locator.3t_vtDk', 'get_ServiceLocator_3tVtDkService.php', true],
    'App\\Controller\\alstomController::delete_project' => ['privates', '.service_locator.Ac1X4cR', 'get_ServiceLocator_Ac1X4cRService.php', true],
    'App\\Controller\\alstomController::delete_train' => ['privates', '.service_locator.59.A7DW', 'get_ServiceLocator_59_A7DWService.php', true],
    'App\\Controller\\alstomController::edit_client' => ['privates', '.service_locator._IXm1YU', 'get_ServiceLocator_IXm1YUService.php', true],
    'App\\Controller\\alstomController::edit_engineer' => ['privates', '.service_locator.tx3hRNe', 'get_ServiceLocator_Tx3hRNeService.php', true],
    'App\\Controller\\alstomController::edit_project' => ['privates', '.service_locator.Ac1X4cR', 'get_ServiceLocator_Ac1X4cRService.php', true],
    'App\\Controller\\alstomController::edit_train' => ['privates', '.service_locator.59.A7DW', 'get_ServiceLocator_59_A7DWService.php', true],
    'App\\Controller\\alstomController::engineers' => ['privates', '.service_locator.MWuXu_8', 'get_ServiceLocator_MWuXu8Service.php', true],
    'App\\Controller\\alstomController::evc' => ['privates', '.service_locator.kRdOC71', 'get_ServiceLocator_KRdOC71Service.php', true],
    'App\\Controller\\alstomController::projects' => ['privates', '.service_locator.MnNiUch', 'get_ServiceLocator_MnNiUchService.php', true],
    'App\\Controller\\alstomController::show_clients' => ['privates', '.service_locator._IXm1YU', 'get_ServiceLocator_IXm1YUService.php', true],
    'App\\Controller\\alstomController::show_engineer' => ['privates', '.service_locator.tx3hRNe', 'get_ServiceLocator_Tx3hRNeService.php', true],
    'App\\Controller\\alstomController::show_project' => ['privates', '.service_locator.Ac1X4cR', 'get_ServiceLocator_Ac1X4cRService.php', true],
    'App\\Controller\\alstomController::show_train' => ['privates', '.service_locator.59.A7DW', 'get_ServiceLocator_59_A7DWService.php', true],
    'App\\Controller\\alstomController::trains' => ['privates', '.service_locator.4qFVQPl', 'get_ServiceLocator_4qFVQPlService.php', true],
    'App\\Controller\\clientController::delete_train' => ['privates', '.service_locator.59.A7DW', 'get_ServiceLocator_59_A7DWService.php', true],
    'App\\Controller\\clientController::edit_train' => ['privates', '.service_locator.59.A7DW', 'get_ServiceLocator_59_A7DWService.php', true],
    'App\\Controller\\clientController::projects' => ['privates', '.service_locator.MnNiUch', 'get_ServiceLocator_MnNiUchService.php', true],
    'App\\Controller\\clientController::show_project' => ['privates', '.service_locator.Ac1X4cR', 'get_ServiceLocator_Ac1X4cRService.php', true],
    'App\\Controller\\clientController::show_train' => ['privates', '.service_locator.59.A7DW', 'get_ServiceLocator_59_A7DWService.php', true],
    'App\\Controller\\clientController::trains' => ['privates', '.service_locator.4qFVQPl', 'get_ServiceLocator_4qFVQPlService.php', true],
    'App\\Controller\\clientController::users' => ['privates', '.service_locator.JkextnA', 'get_ServiceLocator_JkextnAService.php', true],
    'App\\Controller\\securityController::login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\KeyCloakAuthController:connectAction' => ['privates', '.service_locator.no19fnv', 'get_ServiceLocator_No19fnvService.php', true],
    'App\\Controller\\alstomController:baseline' => ['privates', '.service_locator.hzCL1kd', 'get_ServiceLocator_HzCL1kdService.php', true],
    'App\\Controller\\alstomController:clients' => ['privates', '.service_locator.jNTV7Lm', 'get_ServiceLocator_JNTV7LmService.php', true],
    'App\\Controller\\alstomController:delete_baseline' => ['privates', '.service_locator.2hlHMKT', 'get_ServiceLocator_2hlHMKTService.php', true],
    'App\\Controller\\alstomController:delete_client' => ['privates', '.service_locator._IXm1YU', 'get_ServiceLocator_IXm1YUService.php', true],
    'App\\Controller\\alstomController:delete_engineer' => ['privates', '.service_locator.tx3hRNe', 'get_ServiceLocator_Tx3hRNeService.php', true],
    'App\\Controller\\alstomController:delete_evc' => ['privates', '.service_locator.3t_vtDk', 'get_ServiceLocator_3tVtDkService.php', true],
    'App\\Controller\\alstomController:delete_project' => ['privates', '.service_locator.Ac1X4cR', 'get_ServiceLocator_Ac1X4cRService.php', true],
    'App\\Controller\\alstomController:delete_train' => ['privates', '.service_locator.59.A7DW', 'get_ServiceLocator_59_A7DWService.php', true],
    'App\\Controller\\alstomController:edit_client' => ['privates', '.service_locator._IXm1YU', 'get_ServiceLocator_IXm1YUService.php', true],
    'App\\Controller\\alstomController:edit_engineer' => ['privates', '.service_locator.tx3hRNe', 'get_ServiceLocator_Tx3hRNeService.php', true],
    'App\\Controller\\alstomController:edit_project' => ['privates', '.service_locator.Ac1X4cR', 'get_ServiceLocator_Ac1X4cRService.php', true],
    'App\\Controller\\alstomController:edit_train' => ['privates', '.service_locator.59.A7DW', 'get_ServiceLocator_59_A7DWService.php', true],
    'App\\Controller\\alstomController:engineers' => ['privates', '.service_locator.MWuXu_8', 'get_ServiceLocator_MWuXu8Service.php', true],
    'App\\Controller\\alstomController:evc' => ['privates', '.service_locator.kRdOC71', 'get_ServiceLocator_KRdOC71Service.php', true],
    'App\\Controller\\alstomController:projects' => ['privates', '.service_locator.MnNiUch', 'get_ServiceLocator_MnNiUchService.php', true],
    'App\\Controller\\alstomController:show_clients' => ['privates', '.service_locator._IXm1YU', 'get_ServiceLocator_IXm1YUService.php', true],
    'App\\Controller\\alstomController:show_engineer' => ['privates', '.service_locator.tx3hRNe', 'get_ServiceLocator_Tx3hRNeService.php', true],
    'App\\Controller\\alstomController:show_project' => ['privates', '.service_locator.Ac1X4cR', 'get_ServiceLocator_Ac1X4cRService.php', true],
    'App\\Controller\\alstomController:show_train' => ['privates', '.service_locator.59.A7DW', 'get_ServiceLocator_59_A7DWService.php', true],
    'App\\Controller\\alstomController:trains' => ['privates', '.service_locator.4qFVQPl', 'get_ServiceLocator_4qFVQPlService.php', true],
    'App\\Controller\\clientController:delete_train' => ['privates', '.service_locator.59.A7DW', 'get_ServiceLocator_59_A7DWService.php', true],
    'App\\Controller\\clientController:edit_train' => ['privates', '.service_locator.59.A7DW', 'get_ServiceLocator_59_A7DWService.php', true],
    'App\\Controller\\clientController:projects' => ['privates', '.service_locator.MnNiUch', 'get_ServiceLocator_MnNiUchService.php', true],
    'App\\Controller\\clientController:show_project' => ['privates', '.service_locator.Ac1X4cR', 'get_ServiceLocator_Ac1X4cRService.php', true],
    'App\\Controller\\clientController:show_train' => ['privates', '.service_locator.59.A7DW', 'get_ServiceLocator_59_A7DWService.php', true],
    'App\\Controller\\clientController:trains' => ['privates', '.service_locator.4qFVQPl', 'get_ServiceLocator_4qFVQPlService.php', true],
    'App\\Controller\\clientController:users' => ['privates', '.service_locator.JkextnA', 'get_ServiceLocator_JkextnAService.php', true],
    'App\\Controller\\securityController:login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
])), ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
