<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\MainController' shared autowired service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\framework-bundle\\Controller\\ControllerTrait.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\framework-bundle\\Controller\\AbstractController.php';
include_once $this->targetDirs[3].'\\src\\Controller\\MainController.php';
include_once $this->targetDirs[3].'\\src\\Helper\\Utility.php';

$this->services['App\\Controller\\MainController'] = $instance = new \App\Controller\MainController(($this->privates['App\\Services\\HttpClientKeycloakInterface'] ?? $this->load('getHttpClientKeycloakInterfaceService.php')), ($this->privates['App\\Services\\RancherClient'] ?? $this->load('getRancherClientService.php')), ($this->privates['App\\Helper\\Utility'] ?? ($this->privates['App\\Helper\\Utility'] = new \App\Helper\Utility())), ($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService()));

$instance->setContainer(($this->privates['.service_locator.KTVqfp6'] ?? $this->load('get_ServiceLocator_KTVqfp6Service.php'))->withContext('App\\Controller\\MainController', $this));

return $instance;
