<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.tx3hRNe' shared service.

return $this->privates['.service_locator.tx3hRNe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'engineers' => ['privates', '.errored..service_locator.tx3hRNe.App\\Entity\\Engineers', NULL, 'Cannot autowire service ".service_locator.tx3hRNe": it references class "App\\Entity\\Engineers" but no such service exists.'],
]);
