<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.59.A7DW' shared service.

return $this->privates['.service_locator.59.A7DW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'trains' => ['privates', '.errored..service_locator.59.A7DW.App\\Entity\\Trains', NULL, 'Cannot autowire service ".service_locator.59.A7DW": it references class "App\\Entity\\Trains" but no such service exists.'],
]);
