<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.jNTV7Lm' shared service.

return $this->privates['.service_locator.jNTV7Lm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'clientsRepository' => ['privates', 'App\\Repository\\ClientsRepository', 'getClientsRepositoryService.php', true],
]);
