<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Listener\KeycloakExceptionListener' shared autowired service.

include_once $this->targetDirs[3].'\\src\\Listener\\KeycloakExceptionListener.php';

return $this->privates['App\\Listener\\KeycloakExceptionListener'] = new \App\Listener\KeycloakExceptionListener($this, ($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService()));
