<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Services\RancherClient' shared autowired service.

include_once $this->targetDirs[3].'\\src\\Services\\RancherClientInterface.php';
include_once $this->targetDirs[3].'\\src\\Services\\RancherClient.php';
include_once $this->targetDirs[3].'\\src\\Helper\\Utility.php';

return $this->privates['App\\Services\\RancherClient'] = new \App\Services\RancherClient(($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService()), ($this->privates['App\\Helper\\Utility'] ?? ($this->privates['App\\Helper\\Utility'] = new \App\Helper\Utility())));
