<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator._IXm1YU' shared service.

return $this->privates['.service_locator._IXm1YU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'clients' => ['privates', '.errored..service_locator._IXm1YU.App\\Entity\\Clients', NULL, 'Cannot autowire service ".service_locator._IXm1YU": it references class "App\\Entity\\Clients" but no such service exists.'],
]);
