<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Ac1X4cR' shared service.

return $this->privates['.service_locator.Ac1X4cR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'projects' => ['privates', '.errored..service_locator.Ac1X4cR.App\\Entity\\Projects', NULL, 'Cannot autowire service ".service_locator.Ac1X4cR": it references class "App\\Entity\\Projects" but no such service exists.'],
]);
