<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'knpu.oauth2.registry' shared service.

include_once $this->targetDirs[3].'\\vendor\\knpuniversity\\oauth2-client-bundle\\src\\Client\\ClientRegistry.php';

return $this->services['knpu.oauth2.registry'] = new \KnpU\OAuth2ClientBundle\Client\ClientRegistry($this, []);
